# Auto-generated by grail — this is what Monty actually executes

history = await event_get_history(node_id, history_limit)
lines: list[str] = []
for event in history:
    event_type = str(event.get('event_type', 'Event'))
    summary = str(event.get('summary', ''))
    lines.append(f'- {event_type}: {summary}')
content = '# Recent Activity Summary\n\n'
if lines:
    content = content + '\n'.join(lines)
else:
    content = content + 'No events available.'
await write_file('notes/summary.md', content)
result = 'Summary updated'
result