# Auto-generated by grail — this is what Monty actually executes

children = await graph_get_children()
count = 0
for child in children:
    child_id = child.get('node_id')
    if isinstance(child_id, str) and child_id:
        await send_message(child_id, message)
        count += 1
result = f'Broadcast sent to {count} children.'
result