# Auto-generated by grail — do not edit

message: str

async def graph_get_children(parent_id: str | None = Constant(value=None)) -> list[dict]:
    ...

async def send_message(to_node_id: str, content: str) -> bool:
    ...
