# Auto-generated by grail — this is what Monty actually executes

result = await event_unsubscribe(subscription_id)
if result:
    message = f'Unsubscribed: {subscription_id}'
else:
    message = f'Subscription not found: {subscription_id}'
message