# Auto-generated by grail — this is what Monty actually executes

result = await event_unsubscribe(subscription_id)
if result:
    return f'Unsubscribed: {subscription_id}'
return f'Subscription not found: {subscription_id}'