# Auto-generated by grail — this is what Monty actually executes

result = await send_message(to_node_id, content)
if result:
    return f'Message sent to {to_node_id}'
return f'Failed to send message to {to_node_id}'