# Auto-generated by grail — this is what Monty actually executes

result = await send_message(to_node_id, content)
if result:
    message = f'Message sent to {to_node_id}'
else:
    message = f'Failed to send message to {to_node_id}'
message