# Auto-generated by grail — this is what Monty actually executes

node = await graph_get_node(node_id)
node_type = str(node.get('node_type', 'unknown'))
source_code = str(node.get('source_code', ''))
category = 'general'
if 'test' in source_code:
    category = 'testing'
elif 'http' in source_code or 'request' in source_code:
    category = 'networking'
elif 'class ' in source_code:
    category = 'oop'
content = f'# Categories\n\nType: {node_type}\nPrimary: {category}\n'
await write_file('meta/categories.md', content)
result = f'Categorization updated: {category}'
result