# Auto-generated by grail — this is what Monty actually executes

edges = await graph_get_edges(node_id)
lines: list[str] = []
for edge in edges:
    from_id = str(edge.get('from_id', ''))
    to_id = str(edge.get('to_id', ''))
    edge_type = str(edge.get('edge_type', 'related'))
    lines.append(f'- {edge_type}: {from_id} -> {to_id}')
content = '# Links\n\n'
if lines:
    content = content + '\n'.join(lines)
else:
    content = content + 'No links found.'
await write_file('meta/links.md', content)
return f'Recorded {len(lines)} links'