# Auto-generated by grail — this is what Monty actually executes

payload = {'agent_id': agent_id, 'intent': intent, 'element_type': element_type or 'function'}
sent = await event_emit('ScaffoldRequestEvent', payload)
if sent:
    return f'Scaffold request submitted: {intent}'
return 'Failed to submit scaffold request'