# Auto-generated by grail — do not edit

event_types: str
from_agents: str
path_glob: str

async def event_subscribe(event_types: list[str] | None, from_agents: list[str] | None, path_glob: str | None) -> int:
    ...
