# Auto-generated by grail — this is what Monty actually executes

sent = await send_message(to_node_id, '[runtime] ' + content)
if sent:
    result = 'sent:' + to_node_id
else:
    result = 'failed:' + to_node_id
result