# Auto-generated by grail — this is what Monty actually executes

children = await graph_get_children()
if not children:
    return 'No children found.'
lines = [f"- [{child.get('node_type', '?')}] {child.get('name', '?')} ({child.get('node_id', '?')})" for child in children]
return 'Children:\n' + '\n'.join(lines)