# Auto-generated by grail — this is what Monty actually executes

children = await graph_get_children()
if not children:
    result = 'No children found.'
else:
    lines = [f"- [{child.get('node_type', '?')}] {child.get('name', '?')} ({child.get('node_id', '?')})" for child in children]
    result = 'Children:\n' + '\n'.join(lines)
result