# Auto-generated by grail — this is what Monty actually executes

node_type_value: str | None = node_type.strip() if node_type.strip() else None
agents = await graph_query_nodes(node_type_value, None)
return str(agents)