# Auto-generated by grail — do not edit

max_depth: int

async def graph_query_nodes(node_type: str | None = Constant(value=None), status: str | None = Constant(value=None), file_path: str | None = Constant(value=None)) -> list[dict]:
    ...

async def my_node_id() -> str:
    ...
