# Auto-generated by grail — this is what Monty actually executes

history = await event_get_history(node_id, history_limit)
existing = ''
try:
    existing = await read_file('notes/reflection.md')
except Exception:
    existing = ''
entry = '\n---\nReviewed recent activity.\n'
entry = entry + f'Events observed: {len(history)}\n'
await write_file('notes/reflection.md', existing + entry)
return 'Reflection recorded'