# Auto-generated by grail — do not edit

node_id: str
history_limit: int

async def event_get_history(target_id: str, limit: int) -> list[dict]:
    ...

async def read_file(path: str) -> str:
    ...

async def write_file(path: str, content: str) -> bool:
    ...
